export const projectsConfig = [
    {
        name: 'OddsShopper',
        route: '/projects/odds-shopper',
        githubUrl: '',
        demoUrl: '',
        image: '/projects/odds-shopper/logo.png',
        imageArr: ['/projects/odds-shopper/home.png', '/projects/odds-shopper/header.png', '/projects/odds-shopper/odds.png', '/projects/odds-shopper/modal.png', '/projects/odds-shopper/gamepage-1.png', '/projects/odds-shopper/gamepage-2.png', '/projects/odds-shopper/gamepage-3.png'],
        descriptionBrief: 'The #1 bet shopping tool in the world',
        descriptionLong: 'Built by Awesemo.com. A user can view various bet types for a number of the world’s biggest sports leagues and compare odds across sportsbooks in states where sports betting is legal. A user can also filter for specific players/teams and sportsbooks. In the header navigation, a user can view recent scores and matchups, bet types, and sportsbook offers. On the game page, a user can find a breadth of statistics about a matchup. OddShopper is built using React, Redux, TypeScript, Webpack, Node, Express, and C# (.NET).',
        tools: [
            { name: 'React', url: '/dev/react.svg' },
            { name: 'Redux', url: '/dev/redux.svg' },
            { name: 'TypeScript', url: '/dev/typescript.svg' },
            { name: 'Webpack', url: '/dev/webpack.svg' },
            { name: 'Nodejs', url: '/dev/nodejs.svg' },
            { name: 'Express', url: '/dev/express.svg' },
            { name: 'C# (.NET)', url: '/dev/csharp.svg' },
        ],
    },
    {
        name: 'Rove',
        route: '/projects/rove',
        githubUrl: 'https://github.com/shanesween/Rove',
        demoUrl: '',
        image: '/projects/rove/logo.png',
        descriptionBrief: 'A social media and exploration native app for digital nomads',
        descriptionLong: 'Rove is a native social media app for digital nomads, people who have embraced the traveling lifestyle due to the rapid expansion of remote work. Rove allows users to build out their profile and share posts to their feed. Additionally, users can search, connect, and chat with friends. What makes Rove stand out is its ‘Discover’ tab, where users can find new cities, rate cities they have visited, find users in that city, and view a post feed from that city. Rove was built using React Native, Redux, and Google Firestore.',
        tools: [
            { name: 'React Native', url: '/dev/react.svg' },
            { name: 'Redux', url: '/dev/redux.svg' },
            { name: 'Firebase', url: '/dev/firebase.svg' },
        ],
    },
    {
        name: 'Magasin',
        route: '/projects/magasin',
        githubUrl: 'https://github.com/shanesween/Magasin',
        demoUrl: '',
        image: '/projects/magasin/logo.png',
        descriptionBrief: 'French for Shop - An e-commerce site for knicks & knacks',
        descriptionLong: 'Guests and logged-in users can place items in their shopping cart and checkout (with Stripe). Logged-in users can edit their personal information and view past orders. Magasin administrators can access the admin portal in order to edit product/user info. Magasin was built using React, Redux, SCSS, Node, Express, Sequelize, & PostgreSQL.',
        tools: [
            { name: 'React', url: '/dev/react.svg' },
            { name: 'Redux', url: '/dev/redux.svg' },
            { name: 'Webpack', url: '/dev/webpack.svg' },
            { name: 'Nodejs', url: '/dev/nodejs.svg' },
            { name: 'Express', url: '/dev/express.svg' },
            { name: 'Sequelize', url: '/dev/sequelize.svg' },
            { name: 'Bootstrap', url: '/dev/bootstrap.svg' },
        ],
    },
]